/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    events: Event;
    schedule: Schedule;
    pages: Page;
    zones: Zone;
    taverns: Tavern;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    events: {
      dates: 'schedule';
    };
  };
  collectionsSelect: {
    events: EventsSelect<false> | EventsSelect<true>;
    schedule: ScheduleSelect<false> | ScheduleSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    zones: ZonesSelect<false> | ZonesSelect<true>;
    taverns: TavernsSelect<false> | TavernsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    site: Site;
  };
  globalsSelect: {
    site: SiteSelect<false> | SiteSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * Латиницей, например denvikingi
   */
  slug: string;
  /**
   * Например, 6+
   */
  ageRating?: string | null;
  /**
   * Одна-две фразы для карточки
   */
  summary?: string | null;
  /**
   * Абзацы разделяются пустой строкой
   */
  description?: string | null;
  venue?: string | null;
  tariffs: {
    kind: 'entry' | 'adult' | 'child' | 'family22' | 'family21';
    amount: number;
    id?: string | null;
  }[];
  includes?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  extras?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  gallery?: (number | Media)[] | null;
  /**
   * Только касса Radario: https://radario.ru/…
   */
  ticketUrl: string;
  dates?: {
    docs?: (number | Schedule)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule".
 */
export interface Schedule {
  id: number;
  event: number | Event;
  date: string;
  start: string;
  end: string;
  show?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: 'home' | 'directions' | 'corporate';
  lead?: string | null;
  /**
   * Кадр под заголовком: вечерний для темной темы, дневной для светлой
   */
  hero?: {
    photoNight?: (number | null) | Media;
    photoDay?: (number | null) | Media;
  };
  sections?:
    | (
        | {
            /**
             * Латиницей, для ссылки на раздел с других страниц: /kak-doehat#transfer
             */
            anchor?: string | null;
            heading?: string | null;
            /**
             * Абзацы разделяются пустой строкой
             */
            body?: string | null;
            photo?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            /**
             * Латиницей, для ссылки на раздел с других страниц: /kak-doehat#transfer
             */
            anchor?: string | null;
            heading?: string | null;
            /**
             * Абзацы разделяются пустой строкой
             */
            intro?: string | null;
            items?:
              | {
                  title: string;
                  text?: string | null;
                  /**
                   * Например, расписание автобуса
                   */
                  url?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Абзацы разделяются пустой строкой
             */
            footnote?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'list';
          }
        | {
            /**
             * Латиницей, для ссылки на раздел с других страниц: /kak-doehat#transfer
             */
            anchor?: string | null;
            heading?: string | null;
            /**
             * Абзацы разделяются пустой строкой
             */
            intro?: string | null;
            rows?:
              | {
                  label: string;
                  amount: number;
                  /**
                   * Например, «час» или «одно место»
                   */
                  unit?: string | null;
                  note?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Абзацы разделяются пустой строкой
             */
            footnote?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'prices';
          }
        | {
            /**
             * Латиницей, для ссылки на раздел с других страниц: /kak-doehat#transfer
             */
            anchor?: string | null;
            heading?: string | null;
            links?:
              | {
                  label: string;
                  url: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'links';
          }
        | {
            /**
             * Латиницей, для ссылки на раздел с других страниц: /kak-doehat#transfer
             */
            anchor?: string | null;
            heading?: string | null;
            photos?: (number | Media)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'photos';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zones".
 */
export interface Zone {
  id: number;
  name: string;
  /**
   * Латиницей, например denvikingi
   */
  slug: string;
  /**
   * Значок на плитке площадки на главной
   */
  mark?: ('house' | 'forge' | 'pot' | 'bow' | 'shield' | 'ship' | 'hall' | 'horn') | null;
  /**
   * Абзацы разделяются пустой строкой
   */
  description?: string | null;
  photo?: (number | null) | Media;
  /**
   * Меньше — выше
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taverns".
 */
export interface Tavern {
  id: number;
  name: string;
  /**
   * Латиницей, например denvikingi
   */
  slug: string;
  /**
   * Абзацы разделяются пустой строкой
   */
  description?: string | null;
  photo?: (number | null) | Media;
  /**
   * Меньше — выше
   */
  order: number;
  menu?:
    | {
        title?: string | null;
        items?:
          | {
              name: string;
              note?: string | null;
              price: number;
              /**
               * Если цена — вилка
               */
              priceTo?: number | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'schedule';
        value: number | Schedule;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'zones';
        value: number | Zone;
      } | null)
    | ({
        relationTo: 'taverns';
        value: number | Tavern;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  ageRating?: T;
  summary?: T;
  description?: T;
  venue?: T;
  tariffs?:
    | T
    | {
        kind?: T;
        amount?: T;
        id?: T;
      };
  includes?:
    | T
    | {
        text?: T;
        id?: T;
      };
  extras?:
    | T
    | {
        text?: T;
        id?: T;
      };
  gallery?: T;
  ticketUrl?: T;
  dates?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule_select".
 */
export interface ScheduleSelect<T extends boolean = true> {
  event?: T;
  date?: T;
  start?: T;
  end?: T;
  show?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  lead?: T;
  hero?:
    | T
    | {
        photoNight?: T;
        photoDay?: T;
      };
  sections?:
    | T
    | {
        text?:
          | T
          | {
              anchor?: T;
              heading?: T;
              body?: T;
              photo?: T;
              id?: T;
              blockName?: T;
            };
        list?:
          | T
          | {
              anchor?: T;
              heading?: T;
              intro?: T;
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    url?: T;
                    id?: T;
                  };
              footnote?: T;
              id?: T;
              blockName?: T;
            };
        prices?:
          | T
          | {
              anchor?: T;
              heading?: T;
              intro?: T;
              rows?:
                | T
                | {
                    label?: T;
                    amount?: T;
                    unit?: T;
                    note?: T;
                    id?: T;
                  };
              footnote?: T;
              id?: T;
              blockName?: T;
            };
        links?:
          | T
          | {
              anchor?: T;
              heading?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        photos?:
          | T
          | {
              anchor?: T;
              heading?: T;
              photos?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zones_select".
 */
export interface ZonesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  mark?: T;
  description?: T;
  photo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taverns_select".
 */
export interface TavernsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  photo?: T;
  order?: T;
  menu?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              name?: T;
              note?: T;
              price?: T;
              priceTo?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  name: string;
  tagline?: string | null;
  ageNote?: string | null;
  address: string;
  phone: string;
  email: string;
  /**
   * Строка в подвале
   */
  legal?: string | null;
  socials?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Инструкция той кассы, в которую ведут кнопки билета
   */
  refund?: {
    title?: string | null;
    /**
     * Абзацы разделяются пустой строкой
     */
    body?: string | null;
    email?: string | null;
    details?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  ageNote?: T;
  address?: T;
  phone?: T;
  email?: T;
  legal?: T;
  socials?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  refund?:
    | T
    | {
        title?: T;
        body?: T;
        email?: T;
        details?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}